services:
  - type: web
    name: otakuverse-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node dist/main.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        value: http://localhost:5173
      - key: BACKEND_URL
        sync: false
